cd c:\repos\forth\ 

\ Socket types

0 CONSTANT ZMQ_PAIR
1 CONSTANT ZMQ_PUB
2 CONSTANT ZMQ_SUB
3 CONSTANT ZMQ_REQ
4 CONSTANT ZMQ_REP
5 CONSTANT ZMQ_DEALER
6 CONSTANT ZMQ_ROUTER
7 CONSTANT ZMQ_PULL
8 CONSTANT ZMQ_PUSH
9 CONSTANT ZMQ_XPUB
10 CONSTANT ZMQ_XSUB
11 CONSTANT ZMQ_STREAM


\  Socket options. 
4 CONSTANT ZMQ_AFFINITY
5 CONSTANT ZMQ_ROUTING_ID
6 CONSTANT ZMQ_SUBSCRIBE
7 CONSTANT ZMQ_UNSUBSCRIBE
8 CONSTANT ZMQ_RATE
9 CONSTANT ZMQ_RECOVERY_IVL
11 CONSTANT ZMQ_SNDBUF
12 CONSTANT ZMQ_RCVBUF
13 CONSTANT ZMQ_RCVMORE
14 CONSTANT ZMQ_FD
15 CONSTANT ZMQ_EVENTS
16 CONSTANT ZMQ_TYPE
17 CONSTANT ZMQ_LINGER
18 CONSTANT ZMQ_RECONNECT_IVL
19 CONSTANT ZMQ_BACKLOG
21 CONSTANT ZMQ_RECONNECT_IVL_MAX
22 CONSTANT ZMQ_MAXMSGSIZE
23 CONSTANT ZMQ_SNDHWM
24 CONSTANT ZMQ_RCVHWM
25 CONSTANT ZMQ_MULTICAST_HOPS
27 CONSTANT ZMQ_RCVTIMEO
28 CONSTANT ZMQ_SNDTIMEO
32 CONSTANT ZMQ_LAST_ENDPOINT
33 CONSTANT ZMQ_ROUTER_MANDATORY
34 CONSTANT ZMQ_TCP_KEEPALIVE
35 CONSTANT ZMQ_TCP_KEEPALIVE_CNT
36 CONSTANT ZMQ_TCP_KEEPALIVE_IDLE
37 CONSTANT ZMQ_TCP_KEEPALIVE_INTVL
39 CONSTANT ZMQ_IMMEDIATE
40 CONSTANT ZMQ_XPUB_VERBOSE
41 CONSTANT ZMQ_ROUTER_RAW
42 CONSTANT ZMQ_IPV6
43 CONSTANT ZMQ_MECHANISM
44 CONSTANT ZMQ_PLAIN_SERVER
45 CONSTANT ZMQ_PLAIN_USERNAME
46 CONSTANT ZMQ_PLAIN_PASSWORD
47 CONSTANT ZMQ_CURVE_SERVER
48 CONSTANT ZMQ_CURVE_PUBLICKEY
49 CONSTANT ZMQ_CURVE_SECRETKEY
50 CONSTANT ZMQ_CURVE_SERVERKEY
51 CONSTANT ZMQ_PROBE_ROUTER
52 CONSTANT ZMQ_REQ_CORRELATE
53 CONSTANT ZMQ_REQ_RELAXED
54 CONSTANT ZMQ_CONFLATE
55 CONSTANT ZMQ_ZAP_DOMAIN
56 CONSTANT ZMQ_ROUTER_HANDOVER
57 CONSTANT ZMQ_TOS
61 CONSTANT ZMQ_CONNECT_ROUTING_ID
62 CONSTANT ZMQ_GSSAPI_SERVER
63 CONSTANT ZMQ_GSSAPI_PRINCIPAL
64 CONSTANT ZMQ_GSSAPI_SERVICE_PRINCIPAL
65 CONSTANT ZMQ_GSSAPI_PLAINTEXT
66 CONSTANT ZMQ_HANDSHAKE_IVL
68 CONSTANT ZMQ_SOCKS_PROXY
69 CONSTANT ZMQ_XPUB_NODROP
70 CONSTANT ZMQ_BLOCKY
71 CONSTANT ZMQ_XPUB_MANUAL
72 CONSTANT ZMQ_XPUB_WELCOME_MSG
73 CONSTANT ZMQ_STREAM_NOTIFY
74 CONSTANT ZMQ_INVERT_MATCHING
75 CONSTANT ZMQ_HEARTBEAT_IVL
76 CONSTANT ZMQ_HEARTBEAT_TTL
77 CONSTANT ZMQ_HEARTBEAT_TIMEOUT
78 CONSTANT ZMQ_XPUB_VERBOSER
79 CONSTANT ZMQ_CONNECT_TIMEOUT
80 CONSTANT ZMQ_TCP_MAXRT
81 CONSTANT ZMQ_THREAD_SAFE
84 CONSTANT ZMQ_MULTICAST_MAXTPDU
85 CONSTANT ZMQ_VMCI_BUFFER_SIZE
86 CONSTANT ZMQ_VMCI_BUFFER_MIN_SIZE
87 CONSTANT ZMQ_VMCI_BUFFER_MAX_SIZE
88 CONSTANT ZMQ_VMCI_CONNECT_TIMEOUT
89 CONSTANT ZMQ_USE_FD

\ Message options
1 CONSTANT ZMQ_MORE
3 CONSTANT ZMQ_SHARED

\ send / recv options
1 CONSTANT ZMQ_DONTWAIT 
2 CONSTANT ZMQ_SNDMORE 


LIBRARY libzmq-v120-mt-4_0_4

FUNCTION: zmq_ctx_new ( -- ctx* )
FUNCTION: zmq_socket ( ctx type -- sock* )
FUNCTION: zmq_close ( sock* -- err )
FUNCTION: zmq_bind ( sock* addr* -- err )
FUNCTION: zmq_connect ( sock* addr* -- err )
FUNCTION: zmq_recv ( sock* buff* len flags -- size|err )
FUNCTION: zmq_send ( sock* buff* len flags -- size|err )
FUNCTION: zmq_msg_init ( msg* -- err )
FUNCTION: zmq_msg_init_size ( msg* size -- err )
FUNCTION: zmq_msg_data ( msg* -- data* )
FUNCTION: zmq_msg_send ( msg* sock* flags -- err )
FUNCTION: zmq_msg_recv ( msg* sock* flags -- err )
FUNCTION: zmq_msg_close ( msg* -- err )
FUNCTION: zmq_msg_move ( dest* src* -- err )
FUNCTION: zmq_msg_copy ( dest* src* -- err )
FUNCTION: zmq_msg_more ( msg* -- ismore )
FUNCTION: zmq_msg_size ( msg* -- size )
FUNCTION: zmq_setsockopt ( sock* opt optval* optvallen -- err )
FUNCTION: zmq_getsockopt ( sock* opt optval* optvallen* -- err )

FUNCTION: zmq_errno ( -- errno )
FUNCTION: zmq_strerror ( errno -- str* )

: zmq_geterror zmq_errno zmq_strerror 100 dump ;
